


# example from libevent -- tiny introduction to async I/O

01:
	gcc 01-simple-blocking-http-client.c

02:
	gcc 02-forking-13rot.c


# example in IBM developerworks "Boosting network performance with 
# libev & libevent
#
# to run:
#    ./a.out
#    telnet localhost 8080

03:
	gcc 03-simple-echo-server.c -levent


04:
	gcc 04-builtin-http-server.c -levent -g

05:
	gcc 05-live-update-service-during-news-event.c -levent -g